default:
  server:
    port: 5016
  sessionSecret: 'sso-session-67854345'
  securityAlgorithm: 'aes-256-ctr'
  SSOCookieKey: 'cbs-sso-key-80000'
  db:
    host: 'localhost'
    user: 'root'
    password: '123456789'
    database: 'auth'
  cbssTicketService:
    hostname: 'localhost'
    port    : 5014
    path    : '/api/v1/'
  ldap:
    server: '10.1.4.5:389'
    loginSearchBase: 'OU=Users,OU=User Accounts,OU=Almaty,OU=Kazakhstan,DC=CORP,DC=CBS,DC=KZ'

    updateSearchBase: 'OU=Kazakhstan,DC=CORP,DC=CBS,DC=KZ'
    updateFilter: '(objectCategory=CN=Person,CN=Schema,CN=Configuration,DC=CORP,DC=CBS,DC=KZ)'
